name: run main.py

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: check for changes
        id: git-diff
        run: echo ::set-output name=CHANGED::$(git diff --name-only HEAD HEAD~)
    
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pip install bs4
          pip install pip install pandas
          
      - name: execute py script # run main.py
        run: python main.py
        
      - name: commit and push changes
        if: steps.git-diff.outputs.CHANGED != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "update filenames"
          git push origin HEAD:main
          
     
          
