name: run main.py

on: 
  workflow_dispatch:
  schedule:
    - cron: '33 12 * * *'

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: PPPPPPPPPP
        run: echo "HALLO"
